/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author Marcos
 */
public class MenuV extends javax.swing.JFrame {

    JDialog viewer = new JDialog(new JFrame(), "ReporteStock", true);
    JDialog viewer2 = new JDialog(new JFrame(), "ReporteDeudores", true);
    JDialog viewer3 = new JDialog(new JFrame(), "ReporteVentas", true);
    JDialog viewer4 = new JDialog(new JFrame(), "ReporteEstadoCuenta", true);

    persistencia.Conexion conex = new persistencia.Conexion();

    /**
     * Creates new form MenuV
     */
    public MenuV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuRepStock = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuRepStock1 = new javax.swing.JMenuItem();
        jMenuRepDeu = new javax.swing.JMenuItem();
        jMenuHistVentas1 = new javax.swing.JMenuItem();
        jMenuEstCu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usu.png"))); // NOI18N
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 40, 40));

        jLabel5.setText("Cerrar sesión");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sell gr.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 90, 80));

        jLabel3.setText("Ventas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 620));

        jMenu3.setText("Transacciones");

        jMenuItem11.setText("Ventas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem4.setText("Pagar Credito");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMenuRepStock.setText("consulta de facturas");
        jMenuRepStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepStockActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuRepStock);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        jMenuRepStock1.setText("Reporte de stock");
        jMenuRepStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepStock1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuRepStock1);

        jMenuRepDeu.setText("Reporte de Deudores");
        jMenuRepDeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepDeuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuRepDeu);

        jMenuHistVentas1.setText("Historial de Ventas");
        jMenuHistVentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistVentas1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuHistVentas1);

        jMenuEstCu.setText("Estado de Cuentas");
        jMenuEstCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstCuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuEstCu);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        JFrame aux = new VentanaVenta();
        aux.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuRepStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepStockActionPerformed
        JFrame aux = new ConsultasFacturas();
        aux.setVisible(true);
    }//GEN-LAST:event_jMenuRepStockActionPerformed

    private void jMenuRepStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepStock1ActionPerformed
        try {
            JasperReport reportes = JasperCompileManager.compileReport("C:\\reportes\\ReporteStock.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportes, null, conex.getconexion());

            viewer.setSize(1000, 700);
            viewer.setLocationRelativeTo(null);
            JRViewer jrv = new JRViewer(jasperPrint);
            viewer.getContentPane().add(jrv);
            viewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRepStock1ActionPerformed

    private void jMenuHistVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistVentas1ActionPerformed
        try {
            JasperReport reportes = JasperCompileManager.compileReport("C:\\reportes\\ReporteVentas.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportes, null, conex.getconexion());

            viewer3.setSize(1000, 700);
            viewer3.setLocationRelativeTo(null);
            JRViewer jrv = new JRViewer(jasperPrint);
            viewer3.getContentPane().add(jrv);
            viewer3.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jMenuHistVentas1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        JFrame aux = new Acceso();
        aux.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //this.dispose();
        JFrame aux = new VentanaVenta();
        aux.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFrame aux = new PagarCredito();
        aux.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuRepDeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepDeuActionPerformed

        try {
            JasperReport reported = JasperCompileManager.compileReport("C:\\reportes\\ReporteDeudores.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(reported, null, conex.getconexion());

            viewer2.setSize(1000, 700);
            viewer2.setLocationRelativeTo(null);
            JRViewer jrv = new JRViewer(jasperPrint);
            viewer2.getContentPane().add(jrv);
            viewer2.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRepDeuActionPerformed

    private void jMenuEstCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstCuActionPerformed
        String ced = JOptionPane.showInputDialog("ingrese ci del cliente");
        if ((ced.equals("")) || (ced.equals("0"))) {
            JOptionPane.showMessageDialog(this, "Debe ingresar CI");
        } else if (ced.length() != 8) {
            JOptionPane.showMessageDialog(this, "La CI debe tener 8 dígitos");
        } else {
            int canting = Integer.parseInt(ced);

            try {

                Map parametro = new HashMap();
                parametro.put("ci", canting);
                JasperReport reported = JasperCompileManager.compileReport("C:\\reportes\\RepEst.jrxml");
                JasperPrint jasperPrint = JasperFillManager.fillReport(reported, parametro, conex.getconexion());

                viewer4.setSize(1000, 700);
                viewer4.setLocationRelativeTo(null);
                JRViewer jrv = new JRViewer(jasperPrint);
                viewer4.getContentPane().add(jrv);
                viewer4.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jMenuEstCuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEstCu;
    private javax.swing.JMenuItem jMenuHistVentas1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuRepDeu;
    private javax.swing.JMenuItem jMenuRepStock;
    private javax.swing.JMenuItem jMenuRepStock1;
    // End of variables declaration//GEN-END:variables
}
