/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import persistencia.repositorioProducto;
import static presentacion.VentanaVenta.jTableVenta;

/**
 *
 * @author Matias
 */
public class ProductosB extends javax.swing.JFrame {

    /**
     * Creates new form ProductosB
     */
    public ProductosB() {
        initComponents();
        mostrardatos("");
    }

    void mostrardatos(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("IDENTIFICADOR");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PRECIO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("STOCK");
        jTableProducto.setModel(modelo);

        repositorioProducto.getInstancia().rellenarModeloProductoyStock(modelo, valor);
        jTableProducto.setModel(modelo);

    }
 
   

    public void calcular() {
       String pre;
        String can;
        Integer modelo = null;

        double subtotal = 0;
        Integer precio;
        int cantidad;

        double iva = 0;
        double total = 0;
        double sub = 0;

        double iv = 0;

        double tot = 0;
        /*can=Integer.parseInt(cant);
         imp=pre*can;
         dato[4]=Float.toString(imp);*/
        int fila = jTableProducto.getSelectedRow();

        

        for (int i = 0; i < jTableVenta.getRowCount(); i++) {
        Integer valorTasa = repositorioProducto.getInstancia().obtenerValorIndicador((String) jTableVenta.getValueAt(i, 0), modelo);
            pre = jTableVenta.getValueAt(i, 2).toString();
            can = jTableVenta.getValueAt(i, 3).toString();
            precio = Integer.parseInt(pre);
            cantidad = Integer.parseInt(can);
            total = (precio * cantidad);

            iva = (total * valorTasa / 100);
            subtotal = total - iva;

            jTableVenta.setValueAt(subtotal, i, 4);
            jTableVenta.setValueAt(iva, i, 5);
            jTableVenta.setValueAt(total, i, 6);
            sub = sub + subtotal;
            iv = iv + iva;
            tot = tot + total;
            VentanaVenta.txtSubTotal.setText("" + Math.round(sub * 100) / 100);
            VentanaVenta.txtIV.setText("" + Math.round(iv));
            VentanaVenta.txttotal.setText("" + Math.round(tot));
        

        }

       
    
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnenviar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new JTable(){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };
        txtbuscar = new javax.swing.JTextField();
        btnMostrarProducto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        mnenviar.setText("Enviar a Boleta");
        mnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnenviarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnenviar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar productos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProducto.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jTableProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 370, 100));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 90, -1));

        btnMostrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/show all.png"))); // NOI18N
        btnMostrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 40));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 40));

        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("Mostrar todo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel3.setText("Nuevo producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProductoActionPerformed
      
        mostrardatos("");
        txtbuscar.setText("");
       // btnMostrarProducto.setEnabled(false);
    }//GEN-LAST:event_btnMostrarProductoActionPerformed

    private void mnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnenviarActionPerformed
        // TODO add your handling code here:

      //  try {
            DefaultTableModel tabladet = (DefaultTableModel) VentanaVenta.jTableVenta.getModel();
           // public boolean isCellEditable(int rowIndex, int columnIndex) {
           // return false;  //
            //}
            String[] dato = new String[5];
            int fila = jTableProducto.getSelectedRow();

            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No  ha seleccionado ningun registro");
            } else {
                String cod = jTableProducto.getValueAt(fila, 0).toString();
                String nombre = jTableProducto.getValueAt(fila, 1).toString();
                String precio = jTableProducto.getValueAt(fila, 2).toString();
               
                int c = 0;
                int j = 0;
                String cant = JOptionPane.showInputDialog("ingrese cantidad");
                if ((cant.equals("")) || (cant.equals("0"))) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar algun valor mayor que 0");
                } else {
                    int canting = Integer.parseInt(cant);
                    int comp = Integer.parseInt(repositorioProducto.getInstancia().comparar(cod));
                    if (canting > comp) {
                        JOptionPane.showMessageDialog(this, "Ud. no cuenta con el stock apropiado");

                    } else {
                        for (int i = 0; i < VentanaVenta.jTableVenta.getRowCount(); i++) {
                            Object com = VentanaVenta.jTableVenta.getValueAt(i, 0);
                            if (cod.equals(com)) {
                                j = i;
                                VentanaVenta.jTableVenta.setValueAt(cant, i, 3);
                                c = c + 1;
                                calcular();
                            }
                        }
                        if (c == 0) {
                            dato[0] = cod;
                            dato[1] = nombre;
                            dato[2] = precio;
                            dato[3] = cant;
                            tabladet.addRow(dato);
                            VentanaVenta.jTableVenta.setModel(tabladet);
                            calcular();

                        }
                    }

                }
            }
      //  } catch (Exception e) {
       // }
        

    }//GEN-LAST:event_mnenviarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        mostrardatos(txtbuscar.getText());

    }//GEN-LAST:event_txtbuscarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFrame aux = new ABMProducto();
        aux.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductosB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductosB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductosB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductosB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductosB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JMenuItem mnenviar;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
