package presentacion;

import dominio.apertura_cierre;
import dominio.linea_venta;
import dominio.medioPago;
import dominio.venta;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;
import persistencia.repositorioAperturaCierre;
import persistencia.repositorioMedioPago;
import persistencia.repositorioMovimiento;
import persistencia.repositorioStock;
import persistencia.repositorioUsuario;
import persistencia.repositorioVenta;
import dominio.cliente;

import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JRViewer;
import persistencia.repositorioCliente;
import persistencia.repositorioProducto;
import persistencia.Validar;
import dominio.credito;
import dominio.producto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Action;
import javax.swing.JTable;
import persistencia.repositorioCredito;

/**
 *
 * @author Matias
 */
public class VentanaVenta extends javax.swing.JFrame {

    DefaultComboBoxModel mdlCamara = new DefaultComboBoxModel();

    Validar v = new Validar();
    JDialog viewer = new JDialog(new JFrame(), "ReporteStock", true);
    JDialog viewer2 = new JDialog(new JFrame(), "Historial de Ventas", true);
    JDialog viewer4 = new JDialog(new JFrame(), "Estado de cuenta", true);
    persistencia.Conexion conex = new persistencia.Conexion();

    /**
     * Creates new form VentanaVenta
     */
    public VentanaVenta() {
        initComponents();
        cargarMedio();
        v.validarLetras(txtnombre);
        v.validarLetras(txtape);
        v.validarNumeros(txtTel);
        v.validarNumeros(txtCI);
        String[] turno = {"Credito", "Contado"};
        cboPago.setModel(new javax.swing.DefaultComboBoxModel(turno));
        cboMedio.setEnabled(false);
        txtnombre.setEditable(false);
        txtDire.setEditable(false);
        txttotal.setEditable(false);
        txtSubTotal.setEditable(false);
        txtIV.setEditable(false);
        txtProducto.setEditable(false);
        txtape.setEditable(false);
        txtTel.setEditable(false);
        txtPrecioProducto.setEditable(false);
        numeros();
    }

    void numeros() {
        int j;
        String c = repositorioVenta.getInstancia().obtenerNumFactura();
        if (c == null) {
            txtFac.setText("00000001");
        } else {
            j = Integer.parseInt(c);
            GenerarNumero gen = new GenerarNumero();
            gen.generar(j);
            txtFac.setText(gen.serie());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVenta = new JTable(){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };
        txttotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnven = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtIV = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtape = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDire = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtCant = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboMedio = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        buttonAgregar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cboPago = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtFac = new javax.swing.JTextField();
        txtIVA = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuRepStock = new javax.swing.JMenuItem();
        jMenuHistVentas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuRepStock1 = new javax.swing.JMenuItem();
        jMenuRepDeu = new javax.swing.JMenuItem();
        jMenuHistVentas1 = new javax.swing.JMenuItem();
        jMenuEstCu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search2.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 40, 40));

        jTableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad", "SubTotal", "IVA", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTableVentaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVenta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 640, 170));

        txttotal.setEditable(false);
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 80, -1));

        jLabel11.setText("Vender");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, -1, 10));

        btnven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sell smll.png"))); // NOI18N
        btnven.setToolTipText("");
        btnven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenActionPerformed(evt);
            }
        });
        getContentPane().add(btnven, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 50, 50));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel9.setText("Buscar productos");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel13.setText("Total:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, -1, -1));

        jLabel6.setText("SubTotal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, -1, -1));
        getContentPane().add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 100, -1));

        jLabel14.setText("IVA");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));
        getContentPane().add(txtIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 90, -1));

        txtnombre.setRequestFocusEnabled(false);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 120, -1));

        jLabel2.setText("Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));
        getContentPane().add(txtape, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 120, -1));

        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));
        getContentPane().add(txtDire, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usu2.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 40, 40));

        jLabel12.setText("Buscar cliente");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jLabel5.setText("Teléfono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 120, -1));

        jLabel4.setText("Nro. doc.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIActionPerformed(evt);
            }
        });
        getContentPane().add(txtCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, -1));

        jLabel8.setText("Cod Producto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        txtCodProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProductoActionPerformed(evt);
            }
        });
        txtCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 120, -1));

        jLabel15.setText("Producto");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));
        getContentPane().add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 120, -1));

        jLabel19.setText("Volver");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jLabel16.setText("Precio");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Datos de la venta");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel20.setText("Agregar producto");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));
        getContentPane().add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Datos del producto");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel17.setText("Cant.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Datos del cliente");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 680, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 680, 10));
        getContentPane().add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 120, -1));

        jLabel7.setText("Medio Pago");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        cboMedio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMedioActionPerformed(evt);
            }
        });
        getContentPane().add(cboMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 120, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back3.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 40, 40));

        buttonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 50, 50));

        jLabel18.setText("Tipo de Pago");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        cboPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPagoActionPerformed(evt);
            }
        });
        getContentPane().add(cboPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 100, -1));

        jLabel10.setText("Cod. Fac");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        txtFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacActionPerformed(evt);
            }
        });
        getContentPane().add(txtFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 70, -1));

        txtIVA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        getContentPane().add(txtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 680, 610));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jMenu1.setText("ABM");

        jMenuItem8.setText("Administrar Clientes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Administrar Productos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("Administrar Usuarios del sistema");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setText("Administrar Medios de pago");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Transacciones");

        jMenuItem14.setText("Ventas");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuItem1.setText("Compra de Mercadería");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem15.setText("Baja de Mercadería");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuItem16.setText("Movimiento de caja");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenuItem4.setText("Apertura de caja");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem7.setText("Cerrar Turno");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem12.setText("Pagar Deuda");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMenuRepStock.setText("consulta de facturas");
        jMenuRepStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepStockActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuRepStock);

        jMenuHistVentas.setText("consulta de movimientos de caja");
        jMenuHistVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistVentasActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuHistVentas);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Reportes");

        jMenuRepStock1.setText("Reporte de stock");
        jMenuRepStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepStock1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuRepStock1);

        jMenuRepDeu.setText("Reporte de Deudores");
        jMenuRepDeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepDeuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuRepDeu);

        jMenuHistVentas1.setText("Reporte de ventas");
        jMenuHistVentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistVentas1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuHistVentas1);

        jMenuEstCu.setText("Estado de Cuentas");
        jMenuEstCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstCuActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuEstCu);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ProductosB pro = new ProductosB();
        pro.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenActionPerformed

        String capcod = "", capcan = "";
        double subTotalLinea = 0;
        double IVALinea = 0;
        double TotalLinea = 0;
        Integer modeloo = null;
        repositorioUsuario u = repositorioUsuario.getInstancia();
        Integer idUsuario = u.obtenerIdUsuario(modeloo, Acceso.txtusuario.getText(), Acceso.txtcontra.getText());
        Date d = new Date();
        Integer idA = null;
        if (jTableVenta.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No cargo ningun producto para vender");
        } else {

            String valor = (String) cboPago.getSelectedItem();
            if ("Credito".equals(valor)) {
                if ("".equals(txtCI.getText())) {
                    JOptionPane.showMessageDialog(null, "Debe buscar un cliente para otorgarle el credito");

                } else {
                    Integer codFactura = Integer.parseInt(txtFac.getText());
                    String monto = txttotal.getText();
                    Integer subTotal = Integer.parseInt(txtSubTotal.getText());
                    Integer IVA = Integer.parseInt(txtIV.getText());
                    java.sql.Date fecha = new java.sql.Date(d.getTime());
                    Integer id = repositorioAperturaCierre.getInstancia().seleccionarIdApertura(idA);
                    if (id == null) {
                        JOptionPane.showMessageDialog(null, "Debe iniciar una caja para poder vender");
                    } else if (id != null) {
                        //medioPago med = (medioPago) cboMedio.getSelectedItem();
                        String pago = (String) cboPago.getSelectedItem();
                        repositorioVenta.getInstancia().venta(monto, fecha, pago, 1, id, idUsuario, subTotal, IVA, codFactura);
                        numeros();
                        List<linea_venta> lineas = new ArrayList<linea_venta>();
                        for (int i = 0; i < VentanaVenta.jTableVenta.getRowCount(); i++) {
                            capcod = VentanaVenta.jTableVenta.getValueAt(i, 0).toString();
                            capcan = VentanaVenta.jTableVenta.getValueAt(i, 3).toString();
                            subTotalLinea = Double.parseDouble(VentanaVenta.jTableVenta.getValueAt(i, 4).toString());
                            IVALinea = Double.parseDouble(VentanaVenta.jTableVenta.getValueAt(i, 5).toString());
                            TotalLinea = Double.parseDouble(VentanaVenta.jTableVenta.getValueAt(i, 6).toString());
                            repositorioStock.getInstancia().descontarstock(capcod, capcan);
                            linea_venta linVta = new linea_venta();
                            linVta.setCantidad(capcan);
                            linVta.setIdProducto(capcod);
                            linVta.setSubTotal(subTotalLinea);
                            linVta.setIVA(IVALinea);
                            linVta.setTotal(TotalLinea);
                            lineas.add(linVta);
                        }
                        repositorioVenta.getInstancia().ventalinea(lineas);
                        Integer modelo = null;
                        Integer model = null;
                        Integer idVenta = repositorioVenta.getInstancia().seleccionarIdVenta(modelo);
                        credito cre = new credito();
                        repositorioCliente cli = repositorioCliente.getInstancia();
                        repositorioCredito rep = repositorioCredito.getInstancia();
                        cre.setSaldo(txttotal.getText());
                        cre.setCi_cliente(Integer.parseInt(txtCI.getText()));
                        java.sql.Date fechaVenta = new java.sql.Date(d.getTime());
                        cre.setFechaFin(fechaVenta);
                        cre.setIdVenta(idVenta);
                        rep.guardarCredito(cre);
                        JOptionPane.showMessageDialog(null, "Se realizo la venta con exito");
                        txttotal.setText("");
                        txtCI.setText("");
                        txtDire.setText("");
                        txtTel.setText("");
                        txtnombre.setText("");
                        txtape.setText("");
                        txtSubTotal.setText("");
                        txtIV.setText("");

                    }
                    DefaultTableModel modelo = (DefaultTableModel) jTableVenta.getModel();
                    int a = jTableVenta.getRowCount() - 1;
                    int i;
                    for (i = a; i >= 0; i--) {
                        modelo.removeRow(i);
                    }
                    //cboMedio.setSelectedIndex(0);
                    int seleccion = JOptionPane.showConfirmDialog(null, "Desea factura?");
                    if (seleccion == JOptionPane.YES_OPTION) {
                        Integer model = null;
                        Integer idVenta = repositorioVenta.getInstancia().seleccionarIdVenta(model);

                        try {
                            Map nro = new HashMap();
                            nro.put("nrov", idVenta);

                            JasperReport reporte = JasperCompileManager.compileReport("C:\\reportes\\ReporteFactura.jrxml");
                            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, nro, conex.getconexion());

                            viewer2.setSize(1000, 700);
                            viewer2.setLocationRelativeTo(null);
                            JRViewer jrv = new JRViewer(jasperPrint);
                            viewer2.getContentPane().add(jrv);
                            viewer2.setVisible(true);

                        } catch (JRException ex) {
                            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }
            } else {
                Integer codFactura = Integer.parseInt(txtFac.getText());
                String monto = txttotal.getText();
                Integer subTotal = Integer.parseInt(txtSubTotal.getText());
                Integer IVA = Integer.parseInt(txtIV.getText());
                java.sql.Date fecha = new java.sql.Date(d.getTime());
                Integer id = repositorioAperturaCierre.getInstancia().seleccionarIdApertura(idA);
                if (id == null) {
                    JOptionPane.showMessageDialog(null, "Debe iniciar una caja para poder vender");
                } else if (id != null) {
                    medioPago med = (medioPago) cboMedio.getSelectedItem();
                    Integer medio = med.getIdMedio();
                    String pago = (String) cboPago.getSelectedItem();
                    repositorioVenta.getInstancia().venta(monto, fecha, pago, medio, id, idUsuario, subTotal, IVA,codFactura);
                    numeros();
                    cboMedio.setEnabled(false);
                    List<linea_venta> lineas = new ArrayList<linea_venta>();
                    for (int i = 0; i < VentanaVenta.jTableVenta.getRowCount(); i++) {
                        capcod = VentanaVenta.jTableVenta.getValueAt(i, 0).toString();
                        capcan = VentanaVenta.jTableVenta.getValueAt(i, 3).toString();
                        subTotalLinea = Double.parseDouble(VentanaVenta.jTableVenta.getValueAt(i, 4).toString());
                        IVALinea = Double.parseDouble(VentanaVenta.jTableVenta.getValueAt(i, 5).toString());
                        TotalLinea = Double.parseDouble(VentanaVenta.jTableVenta.getValueAt(i, 6).toString());
                        repositorioStock.getInstancia().descontarstock(capcod, capcan);
                        linea_venta linVta = new linea_venta();
                        linVta.setCantidad(capcan);
                        linVta.setIdProducto(capcod);
                        linVta.setSubTotal(subTotalLinea);
                        linVta.setIVA(IVALinea);
                        linVta.setTotal(TotalLinea);
                        lineas.add(linVta);
                    }
                    repositorioVenta.getInstancia().ventalinea(lineas);
                    JOptionPane.showMessageDialog(null, "Se realizo la venta con exito");
                    txttotal.setText("");
                }
                DefaultTableModel modelo = (DefaultTableModel) jTableVenta.getModel();
                int a = jTableVenta.getRowCount() - 1;
                int i;
                for (i = a; i >= 0; i--) {
                    modelo.removeRow(i);
                }
                cboMedio.setSelectedIndex(0);
                int seleccion = JOptionPane.showConfirmDialog(null, "Desea factura?");
                if (seleccion == JOptionPane.YES_OPTION) {
                    Integer mod = null;
                    Integer idVenta = repositorioVenta.getInstancia().seleccionarIdVenta(mod);

                    try {
                        Map nro = new HashMap();
                        nro.put("nrov", idVenta);

                        JasperReport reporte = JasperCompileManager.compileReport("C:\\reportes\\ReporteFactura.jrxml");
                        JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, nro, conex.getconexion());

                        viewer2.setSize(1000, 700);
                        viewer2.setLocationRelativeTo(null);
                        JRViewer jrv = new JRViewer(jasperPrint);
                        viewer2.getContentPane().add(jrv);
                        viewer2.setVisible(true);

                    } catch (JRException ex) {
                        Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        }


    }//GEN-LAST:event_btnvenActionPerformed

    private void jTableVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableVentaKeyReleased


    }//GEN-LAST:event_jTableVentaKeyReleased

    private void jTableVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableVentaKeyTyped

    }//GEN-LAST:event_jTableVentaKeyTyped

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.dispose();
        JFrame aux = new ABMCliente();
        aux.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        this.dispose();
        JFrame aux = new ABMProducto();

        aux.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.dispose();
        JFrame aux = new ABMUsuario();
        aux.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        this.dispose();
        JFrame aux = new ABMMedioPago();
        aux.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        this.dispose();
        JFrame aux = new VentanaVenta();
        aux.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        JFrame aux = new CompraMercaderia();
        aux.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        this.dispose();
        JFrame aux = new BajaMercaderia();
        aux.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        this.dispose();
        JFrame aux = new MovimientoCaja();
        aux.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
        JFrame aux = new AperturaCaja();
        aux.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.dispose();
        JFrame aux = new CerrarTurno();
        aux.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        this.dispose();
        JFrame aux = new PagarCredito();
        aux.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuRepStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepStockActionPerformed
        this.dispose();
        JFrame aux = new ConsultasFacturas();
        aux.setVisible(true);
    }//GEN-LAST:event_jMenuRepStockActionPerformed

    private void jMenuHistVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistVentasActionPerformed
        this.dispose();
        JFrame aux = new ConsultaMovimiento();
        aux.setVisible(true);
    }//GEN-LAST:event_jMenuHistVentasActionPerformed

    private void jMenuRepStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepStock1ActionPerformed
        this.dispose();
        try {
            JasperReport reportes = JasperCompileManager.compileReport("C:\\reportes\\ReporteStock.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportes, null, conex.getconexion());

            viewer.setSize(1000, 700);
            viewer.setLocationRelativeTo(null);
            JRViewer jrv = new JRViewer(jasperPrint);
            viewer.getContentPane().add(jrv);
            viewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRepStock1ActionPerformed

    private void jMenuRepDeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepDeuActionPerformed
        this.dispose();
        try {
            JasperReport reported = JasperCompileManager.compileReport("C:\\reportes\\ReporteDeudores.jrxml");
            JasperPrint jasperPrint = JasperFillManager.fillReport(reported, null, conex.getconexion());

            viewer2.setSize(1000, 700);
            viewer2.setLocationRelativeTo(null);
            JRViewer jrv = new JRViewer(jasperPrint);
            viewer2.getContentPane().add(jrv);
            viewer2.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuRepDeuActionPerformed

    private void jMenuHistVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistVentas1ActionPerformed
        this.dispose();
        JFrame aux = new BuscadorRepVentas();
        aux.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuHistVentas1ActionPerformed

    private void jMenuEstCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstCuActionPerformed
        String ced = JOptionPane.showInputDialog("ingrese ci del cliente");
        if ((ced.equals("")) || (ced.equals("0"))) {
            JOptionPane.showMessageDialog(this, "Debe ingresar CI");
        } else if (ced.length() != 8) {
            JOptionPane.showMessageDialog(this, "La CI debe tener 8 dígitos");
        } else {
            int canting = Integer.parseInt(ced);
            this.dispose();
            try {

                Map parametro = new HashMap();
                parametro.put("ci", canting);

                JasperReport reported = JasperCompileManager.compileReport("C:\\reportes\\RepEst.jrxml");
                JasperPrint jasperPrint = JasperFillManager.fillReport(reported, parametro, conex.getconexion());

                viewer4.setSize(1000, 700);
                viewer4.setLocationRelativeTo(null);
                JRViewer jrv = new JRViewer(jasperPrint);
                viewer4.getContentPane().add(jrv);
                viewer4.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuEstCuActionPerformed

    private void txtCodProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyTyped

    }//GEN-LAST:event_txtCodProductoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ClienteB cli = new ClienteB();
        cli.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCIActionPerformed

    private void cboMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMedioActionPerformed

    }//GEN-LAST:event_cboMedioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    /*public class txtcodProducto implements KeyListener{

     @Override
     public void keyTyped(KeyEvent ke) {
     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     }

     @Override
     public void keyPressed(KeyEvent ke) {
     int key = ke.getKeyCode();
     if (key == KeyEvent.VK_ENTER) {
          
     JTextField txt_barcode = (JTextField) ke.getSource();
     JOptionPane.showMessageDialog(null,txt_barcode.getText(),"Informacion", JOptionPane.INFORMATION_MESSAGE);
     txt_barcode.setText("");

     }
     }

     @Override
     public void keyReleased(KeyEvent ke) {
     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
     }
        
     }*/
    private void txtCodProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyReleased
        char cteclapress = evt.getKeyChar();

        if (cteclapress == KeyEvent.VK_ENTER) {
            jButton3.doClick();
        }

    }//GEN-LAST:event_txtCodProductoKeyReleased

    private void txtCodProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProductoActionPerformed


    }//GEN-LAST:event_txtCodProductoActionPerformed

    private void txtCodProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyPressed

    }//GEN-LAST:event_txtCodProductoKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        repositorioProducto rep = repositorioProducto.getInstancia();
        producto prodd = rep.buscarProducto(Integer.parseInt(txtCodProducto.getText()));
        if (prodd != null) {
            txtProducto.setText(prodd.getNombre());
            txtPrecioProducto.setText(prodd.getPrecio().toString());
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro el producto buscado");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        Integer modelo = null;
        int c = 0;
        int j = 0;
        DefaultTableModel tabladet = (DefaultTableModel) VentanaVenta.jTableVenta.getModel();
        String[] dato = new String[5];
        String cod = (txtCodProducto.getText());
        String cant = (txtCant.getText());
        String nombre = txtProducto.getText();
        String precio = txtPrecioProducto.getText();
        if ((cant.equals("")) || (cant.equals("0")) || txtCodProducto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar algun valor mayor que 0 o le falta ingresar el codigo de producto");
        } else {
            int canting = Integer.parseInt(cant);
            if ((repositorioStock.getInstancia().obtenerCantidad(modelo, Integer.parseInt(cod)) == null)) {
                JOptionPane.showMessageDialog(null, "No tiene stock registrado de este producto en el sistem");
            } else if (((repositorioStock.getInstancia().obtenerCantidad(modelo, Integer.parseInt(cod)) != null))) {

                int comp = Integer.parseInt(repositorioProducto.getInstancia().comparar(cod));
                if (canting > comp) {
                    JOptionPane.showMessageDialog(this, "Ud. no cuenta con el stock apropiado");

                } else {
                    for (int i = 0; i < VentanaVenta.jTableVenta.getRowCount(); i++) {
                        Object com = VentanaVenta.jTableVenta.getValueAt(i, 0);
                        if (cod.equals(com)) {
                            j = i;
                            VentanaVenta.jTableVenta.setValueAt(cant, i, 3);
                            c = c + 1;
                            calcular();
                        }
                    }
                    if (c == 0) {
                        dato[0] = cod;
                        dato[1] = nombre;
                        dato[2] = precio;
                        dato[3] = cant;
                        tabladet.addRow(dato);
                        VentanaVenta.jTableVenta.setModel(tabladet);
                        calcular();

                    }
                }

            }
        }

    }//GEN-LAST:event_buttonAgregarActionPerformed

    private void cboPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPagoActionPerformed
        if (cboPago.getSelectedItem() == "Contado") {
            cboMedio.setEnabled(true);

        } else if (cboPago.getSelectedItem() == "Credito") {
            cboMedio.setEnabled(false);
        }

    }//GEN-LAST:event_cboPagoActionPerformed

    private void txtFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnven;
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JComboBox cboMedio;
    private javax.swing.JComboBox cboPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEstCu;
    private javax.swing.JMenuItem jMenuHistVentas;
    private javax.swing.JMenuItem jMenuHistVentas1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuRepDeu;
    private javax.swing.JMenuItem jMenuRepStock;
    private javax.swing.JMenuItem jMenuRepStock1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTable jTableVenta;
    public static javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCodProducto;
    public static javax.swing.JTextField txtDire;
    private javax.swing.JTextField txtFac;
    public static javax.swing.JTextField txtIV;
    private javax.swing.JLabel txtIVA;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtProducto;
    public static javax.swing.JTextField txtSubTotal;
    public static javax.swing.JTextField txtTel;
    public static javax.swing.JTextField txtape;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
private void cargarMedio() {
        mdlCamara.removeAllElements();
        cboMedio.setModel(mdlCamara);
        List<medioPago> lista = repositorioMedioPago.getInstancia().listaMedio();
        for (medioPago c : lista) {
            mdlCamara.addElement(c);

        }
    }

    public void calcular() {
        String pre;
        String can;
        Integer modelo = null;
        double subtotal = 0;
        Integer precio;
        int cantidad;

        double iva = 0;
        double total = 0;
        double sub = 0;

        double iv = 0;

        double tot = 0;
        /*can=Integer.parseInt(cant);
         imp=pre*can;
         dato[4]=Float.toString(imp);*/

        for (int i = 0; i < jTableVenta.getRowCount(); i++) {
            Integer valorTasa = repositorioProducto.getInstancia().obtenerValorIndicador((String) jTableVenta.getValueAt(i, 0), modelo);
            pre = jTableVenta.getValueAt(i, 2).toString();
            can = jTableVenta.getValueAt(i, 3).toString();
            precio = Integer.parseInt(pre);
            cantidad = Integer.parseInt(can);
            total = (precio * cantidad);

            iva = (total * valorTasa / 100);
            subtotal = total - iva;

            jTableVenta.setValueAt(subtotal, i, 4);
            jTableVenta.setValueAt(iva, i, 5);
            jTableVenta.setValueAt(total, i, 6);
            sub = sub + subtotal;
            iv = iv + iva;
            tot = tot + total;
            VentanaVenta.txtSubTotal.setText("" + Math.round(sub * 100) / 100);
            VentanaVenta.txtIV.setText("" + Math.round(iv));
            VentanaVenta.txttotal.setText("" + Math.round(tot));

        }

        txtCodProducto.setText("");
        txtProducto.setText("");
        txtPrecioProducto.setText("");
        txtCant.setText("");

    }
}
